(()=>{"use strict";
const C=window.APE16Core,RES=C.RES,CELLS=C.CELLS;
const $=id=>document.getElementById(id), enc=new TextEncoder();
const DEFAULT_PALETTE=["#000000","#4e120a","#6f1b0d","#912812","#b53618","#dd5b1c","#ffaa2d","#ffc44b","#ffd87a","#ffffff"];
const state={
 settings:{collectionName:"APE16",supply:3333,description:"APE16 — a 64×64 pixel-art ape collection.",externalURL:"",imageBaseURI:"",seed:"APE16-GENESIS-3333",genesisName:"Brown"},
 genesis:C.makePixels(),genesisLocked:false,traits:[],conflicts:[],plan:null,editors:{},snapshotKey:"APE16_STUDIO2_SNAPSHOT"
};
function setAppStatus(s){$("appStatus").textContent=s}
function safe(s){return(String(s||"asset").trim().replace(/[^a-z0-9]+/gi,"_").replace(/^_+|_+$/g,"")||"asset")}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},800)}
function pixelsToImageData(p){return new ImageData(new Uint8ClampedArray(p),RES,RES)}
function canvas64FromPixels(p){const c=document.createElement("canvas");c.width=c.height=RES;c.getContext("2d").putImageData(pixelsToImageData(p),0,0);return c}
function renderPixelsToCanvas(p,canvas,size=64){canvas.width=canvas.height=size;const x=canvas.getContext("2d");x.clearRect(0,0,size,size);x.imageSmoothingEnabled=false;x.drawImage(canvas64FromPixels(p),0,0,size,size)}
function hexToRGBA(h){h=h.replace("#","");return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),255]}
function rgbaToHex(c){return "#"+c.slice(0,3).map(v=>v.toString(16).padStart(2,"0")).join("")}
function updateSettingsFromUI(){state.settings={collectionName:$("collectionName").value||"APE16",supply:Number($("supply").value)||3333,description:$("description").value||"",externalURL:$("externalURL").value||"",imageBaseURI:$("imageBaseURI").value||"",seed:$("seed").value||"APE16-GENESIS-3333",genesisName:"Brown"}}
function syncSettingsToUI(){for(const k of ["collectionName","supply","description","externalURL","imageBaseURI","seed"])$(k).value=state.settings[k]??""}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.page).classList.add("active");if(b.dataset.page==="library")renderLibrary();if(b.dataset.page==="generate")state.plan=null});
function newEditor(hostId,mode){
 const host=$(hostId),tpl=$("editorTemplate").content.cloneNode(true);host.appendChild(tpl);const root=host.querySelector(".editorShell");
 const E={mode,root,tool:"pencil",pixels:mode==="genesis"?state.genesis:C.makePixels(),mask:C.makeMask(),history:[],redo:[],palette:[...DEFAULT_PALETTE],color:"#000000",brush:1,mirrorDraw:false,filledRect:false,grid:true,showBase:true,cellPx:10,ref:null,refVisible:true,refOpacity:45,refScale:100,refX:0,refY:0,startCell:null,currentTraitId:null,locked:false};
 state.editors[mode]=E;const q=s=>root.querySelector(s),qa=s=>[...root.querySelectorAll(s)];
 E.canvas=q('[data-role="canvas"]');E.coords=q('[data-role="coords"]');E.modeLabel=q('[data-role="mode"]');E.status=q('[data-role="editorStatus"]');E.validation=q('[data-role="validation"]');E.preview=q('[data-role="preview"]');E.layerPreview=q('[data-role="layerPreview"]');E.colorInput=q('[data-role="color"]');E.paletteEl=q('[data-role="palette"]');
 if(mode==="genesis"){E.modeLabel.textContent="GENESIS LAYER";q('[data-opt="base"]').closest("label").style.display="none";qa('[data-tool="mask"],[data-tool="unmask"]').forEach(x=>x.style.display="none")}else E.modeLabel.textContent="TRAIT PIXELS";
 function hist(){E.history.push({pixels:C.clonePixels(E.pixels),mask:C.cloneMask(E.mask)});if(E.history.length>80)E.history.shift();E.redo=[]}
 function setStatus(s){E.status.textContent=s}
 function renderPalette(){E.paletteEl.innerHTML="";for(const h of E.palette){const b=document.createElement("button");b.className="swatch"+(h.toLowerCase()===E.color.toLowerCase()?" active":"");b.style.background=h;b.title=h;b.onclick=()=>{E.color=h;E.colorInput.value=h;renderPalette()};E.paletteEl.appendChild(b)}}
 E.colorInput.oninput=e=>{E.color=e.target.value;renderPalette()};
 q('[data-action="addColor"]').onclick=()=>{const h=E.colorInput.value;if(!E.palette.includes(h)){E.palette.push(h);renderPalette()}};
 qa("[data-tool]").forEach(b=>b.onclick=()=>{qa("[data-tool]").forEach(x=>x.classList.remove("active"));b.classList.add("active");E.tool=b.dataset.tool});
 q('[data-opt="brush"]').onchange=e=>E.brush=Number(e.target.value);q('[data-opt="mirrorDraw"]').onchange=e=>E.mirrorDraw=e.target.checked;q('[data-opt="filledRect"]').onchange=e=>E.filledRect=e.target.checked;q('[data-opt="grid"]').onchange=e=>{E.grid=e.target.checked;drawEditor(E)};q('[data-opt="base"]').onchange=e=>{E.showBase=e.target.checked;drawEditor(E)};q('[data-opt="zoom"]').onchange=e=>{E.cellPx=Number(e.target.value);drawEditor(E)};
 q('[data-action="undo"]').onclick=()=>{if(!E.history.length)return;E.redo.push({pixels:C.clonePixels(E.pixels),mask:C.cloneMask(E.mask)});const s=E.history.pop();E.pixels=s.pixels;E.mask=s.mask;commitEditorState(E);drawEditor(E)};
 q('[data-action="redo"]').onclick=()=>{if(!E.redo.length)return;E.history.push({pixels:C.clonePixels(E.pixels),mask:C.cloneMask(E.mask)});const s=E.redo.pop();E.pixels=s.pixels;E.mask=s.mask;commitEditorState(E);drawEditor(E)};
 q('[data-action="clear"]').onclick=()=>{if(E.locked)return;hist();E.pixels=C.makePixels();if(mode==="trait")E.mask=C.makeMask();commitEditorState(E);drawEditor(E)};
 q('[data-action="mirror"]').onclick=()=>{if(E.locked)return;hist();if(E.tool==="mask"||E.tool==="unmask")E.mask=C.mirrorMask(E.mask);else E.pixels=C.mirrorPixels(E.pixels);commitEditorState(E);drawEditor(E)};
 const refFile=q('[data-ref="file"]');refFile.onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{E.ref=im;E.refVisible=true;q('[data-action="toggleRef"]').textContent="Reference ON";drawEditor(E)};im.src=r.result};r.readAsDataURL(f)};
 q('[data-ref="opacity"]').oninput=e=>{E.refOpacity=Number(e.target.value);drawEditor(E)};q('[data-ref="scale"]').oninput=e=>{E.refScale=Number(e.target.value);drawEditor(E)};q('[data-ref="x"]').oninput=e=>{E.refX=Number(e.target.value);drawEditor(E)};q('[data-ref="y"]').oninput=e=>{E.refY=Number(e.target.value);drawEditor(E)};
 q('[data-action="toggleRef"]').onclick=()=>{E.refVisible=!E.refVisible;q('[data-action="toggleRef"]').textContent=E.refVisible?"Reference ON":"Reference OFF";drawEditor(E)};
 q('[data-import="layer"]').onchange=e=>importExactLayer(E,e.target.files?.[0]);
 q('[data-action="export64"]').onclick=()=>exportEditorPNG(E,64);q('[data-action="export1024"]').onclick=()=>exportEditorPNG(E,1024);q('[data-action="export4096"]').onclick=()=>exportEditorPNG(E,4096);
 function point(ev){const r=E.canvas.getBoundingClientRect();return [Math.max(0,Math.min(63,Math.floor((ev.clientX-r.left)/r.width*64))),Math.max(0,Math.min(63,Math.floor((ev.clientY-r.top)/r.height*64)))]}
 let down=false,last=null;
 E.canvas.onpointerdown=ev=>{ev.preventDefault();E.canvas.setPointerCapture?.(ev.pointerId);const [x,y]=point(ev);pointerStart(E,x,y,hist);down=true;last=[x,y]};
 E.canvas.onpointermove=ev=>{const [x,y]=point(ev);E.coords.textContent=`x: ${x} · y: ${y} · cell: ${C.idx(x,y)}`;if(down&&["pencil","eraser","mask","unmask"].includes(E.tool)&&(last[0]!==x||last[1]!==y)){pointerPaint(E,x,y);last=[x,y]}};
 E.canvas.onpointerup=ev=>{if(!down)return;const [x,y]=point(ev);pointerEnd(E,x,y);down=false;last=null};
 E.canvas.onpointercancel=()=>{down=false;last=null};
 renderPalette();drawEditor(E);return E
}
function pointerStart(E,x,y,hist){
 if(E.locked){E.status.textContent="LOCKED — create a revision to edit.";return}
 if(E.tool==="picker"){const c=C.rgbaAt(E.pixels,x,y);if(c[3]){E.color=rgbaToHex(c);E.colorInput.value=E.color;E.root.querySelector('[data-action="addColor"]').click()}return}
 hist();E.startCell=[x,y];
 if(["pencil","eraser","mask","unmask"].includes(E.tool))pointerPaint(E,x,y);
 else if(E.tool==="fill"){C.floodFill(E.pixels,x,y,hexToRGBA(E.color));commitEditorState(E);drawEditor(E)}
}
function pointerPaint(E,x,y){
 if(E.locked)return;if(E.tool==="pencil")C.applyBrush(E.pixels,x,y,hexToRGBA(E.color),E.brush,E.mirrorDraw);
 if(E.tool==="eraser")C.applyBrush(E.pixels,x,y,[0,0,0,0],E.brush,E.mirrorDraw);
 if(E.tool==="mask")C.applyMaskBrush(E.mask,x,y,1,E.brush,E.mirrorDraw);
 if(E.tool==="unmask")C.applyMaskBrush(E.mask,x,y,0,E.brush,E.mirrorDraw);
 commitEditorState(E);drawEditor(E)
}
function pointerEnd(E,x,y){
 if(E.locked||!E.startCell)return;const [sx,sy]=E.startCell;
 if(E.tool==="line"){for(const [px,py] of C.lineCells(sx,sy,x,y))C.applyBrush(E.pixels,px,py,hexToRGBA(E.color),E.brush,E.mirrorDraw)}
 if(E.tool==="rect"){for(const [px,py] of C.rectCells(sx,sy,x,y,E.filledRect))C.applyBrush(E.pixels,px,py,hexToRGBA(E.color),1,E.mirrorDraw)}
 E.startCell=null;commitEditorState(E);drawEditor(E)
}
function commitEditorState(E){
 if(E.mode==="genesis"){state.genesis=E.pixels}
 else if(E.currentTraitId){const t=state.traits.find(x=>x.id===E.currentTraitId);if(t&&!t.approved){t.pixels=E.pixels;t.mask=E.mask}}
}
function drawEditor(E){
 const cp=E.cellPx,size=RES*cp,cv=E.canvas;cv.width=cv.height=size;const x=cv.getContext("2d");x.clearRect(0,0,size,size);
 // transparency checker
 for(let y=0;y<RES;y++)for(let xx=0;xx<RES;xx++){x.fillStyle=((xx+y)&1)?"#d5d5d5":"#ffffff";x.fillRect(xx*cp,y*cp,cp,cp)}
 // locked genesis under traits
 if(E.mode==="trait"&&E.showBase&&state.genesis){x.globalAlpha=.35;drawPixelsScaled(x,state.genesis,cp);x.globalAlpha=1}
 // reference overlay
 if(E.ref&&E.refVisible){x.save();x.globalAlpha=E.refOpacity/100;const base=size*(E.refScale/100),w=base,h=base*(E.ref.height/E.ref.width);const dx=(size-w)/2+E.refX*cp,dy=(size-h)/2+E.refY*cp;x.imageSmoothingEnabled=true;x.drawImage(E.ref,dx,dy,w,h);x.restore()}
 // trait/genesis pixels
 drawPixelsScaled(x,E.pixels,cp);
 // show mask as magenta overlay
 if(E.mode==="trait"&&(E.tool==="mask"||E.tool==="unmask")){x.save();x.globalAlpha=.35;x.fillStyle="#ff00aa";for(let c=0;c<CELLS;c++)if(E.mask[c]){let px=c%64,py=Math.floor(c/64);x.fillRect(px*cp,py*cp,cp,cp)}x.restore()}
 if(E.grid){x.strokeStyle="rgba(50,50,50,.35)";x.lineWidth=1;for(let i=0;i<=64;i++){x.beginPath();x.moveTo(i*cp+.5,0);x.lineTo(i*cp+.5,size);x.stroke();x.beginPath();x.moveTo(0,i*cp+.5);x.lineTo(size,i*cp+.5);x.stroke()}}
 drawPreviews(E);updateValidation(E)
}
function drawPixelsScaled(ctx,p,cp){for(let i=0;i<p.length;i+=4)if(p[i+3]){const c=i/4,x=c%64,y=Math.floor(c/64);ctx.fillStyle=`rgb(${p[i]},${p[i+1]},${p[i+2]})`;ctx.fillRect(x*cp,y*cp,cp,cp)}}
function drawPreviews(E){renderPixelsToCanvas(E.pixels,E.layerPreview,64);let comp;if(E.mode==="genesis")comp=E.pixels;else{const temp={category:$("traitCategory").value||"Headwear",none:false,pixels:E.pixels,mask:E.mask};comp=C.compose(state.genesis,[temp])}renderPixelsToCanvas(comp,E.preview,64)}
function updateValidation(E){const a=C.validatePixels(E.pixels,{allowEmpty:E.mode==="trait"&&$("noneTrait")?.checked}),m=E.mode==="trait"?C.validateMask(E.mask):null;E.validation.innerHTML=`<p class="${a.pass?"pass":"fail"}"><b>${a.pass?"PIXEL PASS":"PIXEL FAIL"}</b><br>Painted ${a.painted}/4096 · Transparent ${a.transparent} · Partial alpha ${a.partialAlpha} · Colors ${a.colors}${m?`<br>Mask ${m.pass?"PASS":"FAIL"} · ${m.masked} cells`:""}</p>`}
async function importExactLayer(E,file){if(!file)return;if(E.locked){E.status.textContent="LOCKED — create a revision before importing a layer.";return;}const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{if(im.width!==64||im.height!==64){E.status.textContent=`REJECTED: production layer must be exactly 64×64. Selected ${im.width}×${im.height}. Use it as a Reference Image instead.`;return}const c=document.createElement("canvas");c.width=c.height=64;const x=c.getContext("2d",{willReadFrequently:true});x.clearRect(0,0,64,64);x.drawImage(im,0,0);const d=x.getImageData(0,0,64,64).data,p=C.makePixels();for(let i=0;i<d.length;i+=4){if(d[i+3]!==0&&d[i+3]!==255){E.status.textContent="REJECTED: partial alpha / antialiased pixels found.";return}p[i]=d[i];p[i+1]=d[i+1];p[i+2]=d[i+2];p[i+3]=d[i+3]}E.history.push({pixels:C.clonePixels(E.pixels),mask:C.cloneMask(E.mask)});E.pixels=p;commitEditorState(E);drawEditor(E);E.status.textContent="Exact 64×64 layer imported."};im.src=r.result};r.readAsDataURL(file)}
async function exportEditorPNG(E,size){const p=E.mode==="genesis"?state.genesis:E.pixels;const c=document.createElement("canvas");c.width=c.height=size;const x=c.getContext("2d");x.imageSmoothingEnabled=false;x.drawImage(canvas64FromPixels(p),0,0,size,size);const b=await new Promise(r=>c.toBlob(r,"image/png"));download(b,`${E.mode==="genesis"?"Brown_Genesis":safe($("traitName").value||"Trait")}_${size}.png`)}
function canvas64FromPixels(p){return canvas64FromPixelsImpl(p)}function canvas64FromPixelsImpl(p){const c=document.createElement("canvas");c.width=c.height=64;c.getContext("2d").putImageData(pixelsToImageData(p),0,0);return c}
async function loadGenesis(){
 const im=new Image();im.onload=()=>{const c=document.createElement("canvas");c.width=c.height=64;const x=c.getContext("2d",{willReadFrequently:true});x.drawImage(im,0,0);state.genesis=new Uint8ClampedArray(x.getImageData(0,0,64,64).data);state.editors.genesis.pixels=state.genesis;drawEditor(state.editors.genesis);setAppStatus("READY")};im.onerror=()=>setAppStatus("GENESIS LOAD FAIL");im.src="APE16_BROWN_GENESIS_64x64.png?v=2.0.0"
}
const GE=newEditor("genesisEditor","genesis"),TE=newEditor("traitEditor","trait");
C.LAYERS.forEach(c=>{if(c!=="Body"||true){const o=document.createElement("option");o.value=o.textContent=c;$("traitCategory").appendChild(o)}});
$("auditGenesis").onclick=()=>{const a=C.validatePixels(state.genesis);$("genesisReport").textContent=`${a.pass?"PASS":"FAIL"}\nGrid: 64×64\nPainted: ${a.painted}/4096\nTransparent: ${a.transparent}\nPartial alpha: ${a.partialAlpha}\nColors: ${a.colors}\n${a.issues.join("\n")}`;setAppStatus(a.pass?"GENESIS PASS":"GENESIS FAIL")};
$("lockGenesis").onclick=()=>{const a=C.validatePixels(state.genesis);if(!a.pass)return alert("Genesis must pass audit first.");state.genesisLocked=true;GE.locked=true;$("lockGenesis").disabled=true;setAppStatus("GENESIS LOCKED");saveLightSnapshot()};
$("newTrait").onclick=()=>{if(!state.genesisLocked)return alert("Lock Genesis first.");const existing=state.traits.find(t=>!t.approved&&!t.archived);if(existing)return alert("Finish or discard the current working trait before starting another.");const name=$("traitName").value.trim();if(!name)return alert("Enter a trait name.");const t={id:crypto.randomUUID?crypto.randomUUID():Date.now()+"",category:$("traitCategory").value,name,weight:Number($("traitWeight").value)||0,none:$("noneTrait").checked,revision:1,approved:false,pixels:C.makePixels(),mask:C.makeMask()};state.traits.push(t);TE.currentTraitId=t.id;TE.pixels=t.pixels;TE.mask=t.mask;TE.locked=false;TE.history=[];TE.redo=[];$("approveTrait").disabled=true;$("newRevision").disabled=true;drawEditor(TE);renderLibrary();setAppStatus("TRAIT EDITING")};
$("discardTrait").onclick=()=>{const t=state.traits.find(x=>x.id===TE.currentTraitId);if(!t||t.approved){TE.currentTraitId=null;TE.pixels=C.makePixels();TE.mask=C.makeMask();TE.locked=false;drawEditor(TE);return}if(!confirm("Discard this working trait?"))return;state.traits=state.traits.filter(x=>x.id!==t.id);TE.currentTraitId=null;TE.pixels=C.makePixels();TE.mask=C.makeMask();TE.locked=false;TE.history=[];TE.redo=[];$("traitName").value="";$("noneTrait").checked=false;$("approveTrait").disabled=true;$("newRevision").disabled=true;drawEditor(TE);renderLibrary();setAppStatus("WORKING TRAIT DISCARDED")};
$("noneTrait").onchange=()=>{const t=state.traits.find(x=>x.id===TE.currentTraitId);if(t&&!t.approved){t.none=$("noneTrait").checked;if(t.none){TE.pixels=C.makePixels();TE.mask=C.makeMask();t.pixels=TE.pixels;t.mask=TE.mask;drawEditor(TE)}}};
$("validateTrait").onclick=()=>{const t=state.traits.find(x=>x.id===TE.currentTraitId);if(!t)return alert("Create or load a trait first.");t.category=$("traitCategory").value;t.name=$("traitName").value.trim()||t.name;t.weight=Number($("traitWeight").value)||0;t.none=$("noneTrait").checked;t.pixels=TE.pixels;t.mask=TE.mask;const a=C.validatePixels(t.pixels,{allowEmpty:t.none}),m=C.validateMask(t.mask),dup=state.traits.some(x=>x.id!==t.id&&x.category===t.category&&x.name.toLowerCase()===t.name.toLowerCase());const issues=[...a.issues,...m.issues];if(dup)issues.push("Duplicate category + trait name.");if(t.weight<0)issues.push("Negative rarity weight.");$("traitReport").textContent=`${issues.length?"FAIL":"PASS"}\n${t.category} / ${t.name}\nPixels: ${a.painted}/4096 · Partial alpha ${a.partialAlpha} · Colors ${a.colors}\nMask: ${m.masked} cells\n${issues.join("\n")}`;$("approveTrait").disabled=issues.length>0;setAppStatus(issues.length?"TRAIT FAIL":"TRAIT PASS")};
$("approveTrait").onclick=()=>{const t=state.traits.find(x=>x.id===TE.currentTraitId);if(!t)return;for(const old of state.traits)if(old.id!==t.id&&old.approved&&!old.archived&&old.category===t.category&&old.name.toLowerCase()===t.name.toLowerCase())old.archived=true;t.approved=true;t.archived=false;TE.locked=true;$("approveTrait").disabled=true;$("newRevision").disabled=false;renderLibrary();setAppStatus("TRAIT LOCKED");saveLightSnapshot()};
$("newRevision").onclick=()=>{const old=state.traits.find(x=>x.id===TE.currentTraitId);if(!old||!old.approved)return;const t={...old,id:crypto.randomUUID?crypto.randomUUID():Date.now()+"",revision:(old.revision||1)+1,approved:false,pixels:C.clonePixels(old.pixels),mask:C.cloneMask(old.mask)};state.traits.push(t);TE.currentTraitId=t.id;TE.pixels=t.pixels;TE.mask=t.mask;TE.locked=false;$("traitName").value=t.name;$("traitCategory").value=t.category;$("traitWeight").value=t.weight;$("noneTrait").checked=t.none;$("newRevision").disabled=true;drawEditor(TE);renderLibrary();setAppStatus("REVISION EDITING")};
$("loadApprovedTrait").onclick=()=>{const sel=$("assetLibrary").querySelector("input[name=assetSelect]:checked");if(!sel)return alert("Select an approved trait in Library first.");const old=state.traits.find(x=>x.id===sel.value);if(!old)return;const t={...old,id:crypto.randomUUID?crypto.randomUUID():Date.now()+"",revision:(old.revision||1)+1,approved:false,pixels:C.clonePixels(old.pixels),mask:C.cloneMask(old.mask)};state.traits.push(t);TE.currentTraitId=t.id;TE.pixels=t.pixels;TE.mask=t.mask;TE.locked=false;$("traitName").value=t.name;$("traitCategory").value=t.category;$("traitWeight").value=t.weight;$("noneTrait").checked=t.none;drawEditor(TE);setAppStatus("REVISION EDITING")};
function renderLibrary(){const h=$("assetLibrary");h.innerHTML="";const approved=state.traits.filter(t=>t.approved&&!t.archived);if(!approved.length){h.textContent="No approved traits yet."}for(const t of approved){const r=document.createElement("div");r.className="assetRow";r.innerHTML=`<label class="inline"><input type="radio" name="assetSelect" value="${t.id}"><span><b>${t.category}</b> · ${t.name} · weight ${t.weight} · rev ${t.revision}${t.none?" · None":""}${t.mask.some(v=>v)?" · mask":""}</span></label><button data-id="${t.id}">Delete</button>`;r.querySelector("button").onclick=()=>{if(confirm("Delete this approved trait?")){state.traits=state.traits.filter(x=>x.id!==t.id);state.conflicts=state.conflicts.filter(([a,b])=>a!==C.traitKey(t)&&b!==C.traitKey(t));renderLibrary()}};h.appendChild(r)}renderRuleSelectors()}
function renderRuleSelectors(){for(const id of ["ruleA","ruleB"]){const s=$(id);s.innerHTML="";for(const t of state.traits.filter(x=>x.approved&&!x.archived)){const o=document.createElement("option");o.value=C.traitKey(t);o.textContent=`${t.category} / ${t.name}`;s.appendChild(o)}}renderConflicts()}
$("addConflict").onclick=()=>{const a=$("ruleA").value,b=$("ruleB").value;if(!a||!b||a===b)return;if(!state.conflicts.some(([x,y])=>(x===a&&y===b)||(x===b&&y===a)))state.conflicts.push([a,b]);renderConflicts()};
function renderConflicts(){$("conflictList").innerHTML=state.conflicts.map((r,i)=>`<div class="conflictRow"><span>${r[0]} ✕ ${r[1]}</span><button data-i="${i}">Remove</button></div>`).join("")||"No conflicts.";[...$("conflictList").querySelectorAll("button")].forEach(b=>b.onclick=()=>{state.conflicts.splice(Number(b.dataset.i),1);renderConflicts()})}
function approvedTraits(){return state.traits.filter(t=>t.approved&&!t.archived)}
function productionTraitsFromPlanItem(item){return item.map(i=>state.traits.find(t=>t.approved&&!t.archived&&t.category===i.category&&t.name===i.name)).filter(Boolean)}
function plan(n){updateSettingsFromUI();const p=C.generatePlan({traits:approvedTraits(),conflicts:state.conflicts,supply:n,seed:state.settings.seed,maxAttempts:n*1500});return p}
$("preview24").onclick=()=>{const p=plan(24);$("generateReport").textContent=`${p.pass?"PASS":"PARTIAL"} · ${p.unique}/${p.requested} unique combos · ${p.tries} attempts`;const h=$("previewGrid");h.innerHTML="";for(const item of p.items){const cv=document.createElement("canvas");cv.width=cv.height=64;renderPixelsToCanvas(C.compose(state.genesis,productionTraitsFromPlanItem(item)),cv,64);h.appendChild(cv)}};
$("plan3333").onclick=()=>{state.plan=plan(3333);$("generateReport").textContent=`${state.plan.pass?"PASS":"FAIL"}\nUnique combinations: ${state.plan.unique}/3333\nAttempts: ${state.plan.tries}\n${state.plan.pass?"Full supply achievable.":"Add traits/None weights or relax conflicts before production."}`;setAppStatus(state.plan.pass?"3333 PLAN PASS":"PLAN FAIL")};
function projectForCore(){updateSettingsFromUI();return {settings:{...state.settings},genesisLocked:state.genesisLocked,genesis:state.genesis,traits:state.traits.map(t=>({...t})),conflicts:state.conflicts.map(x=>[...x])}}
$("saveProject").onclick=()=>{const o=C.serializeProject(projectForCore());download(new Blob([JSON.stringify(o,null,2)],{type:"application/json"}),`${safe(state.settings.collectionName)}_Studio2_Project.json`);$("projectStatus").textContent="Editable project downloaded."};
$("loadProject").onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=C.deserializeProject(JSON.parse(r.result));state.settings=p.settings;state.genesisLocked=p.genesisLocked;state.genesis=p.genesis;state.traits=p.traits;state.conflicts=p.conflicts;syncSettingsToUI();GE.pixels=state.genesis;GE.locked=state.genesisLocked;$("lockGenesis").disabled=state.genesisLocked;drawEditor(GE);TE.currentTraitId=null;TE.pixels=C.makePixels();TE.mask=C.makeMask();drawEditor(TE);renderLibrary();$("projectStatus").textContent="Project loaded.";setAppStatus("PROJECT LOADED")}catch(err){alert(err.message)}};r.readAsText(f)};
function saveLightSnapshot(){try{localStorage.setItem(state.snapshotKey,JSON.stringify(C.serializeProject(projectForCore())));$("projectStatus").textContent="Browser snapshot saved."}catch(e){$("projectStatus").textContent="Snapshot unavailable — use Save Editable Project."}}
$("snapshot").onclick=saveLightSnapshot;$("restoreSnapshot").onclick=()=>{const raw=localStorage.getItem(state.snapshotKey);if(!raw)return alert("No browser snapshot.");try{const p=C.deserializeProject(JSON.parse(raw));state.settings=p.settings;state.genesisLocked=p.genesisLocked;state.genesis=p.genesis;state.traits=p.traits;state.conflicts=p.conflicts;syncSettingsToUI();GE.pixels=state.genesis;GE.locked=state.genesisLocked;$("lockGenesis").disabled=state.genesisLocked;drawEditor(GE);renderLibrary();$("projectStatus").textContent="Browser snapshot restored.";setAppStatus("SNAPSHOT RESTORED")}catch(e){alert(e.message)}};
function fullAudit(){updateSettingsFromUI();const a=C.auditProject(projectForCore());if(state.settings.supply!==3333)a.issues.push("APE16 production supply must be 3,333.");const p=plan(3333);if(!p.pass)a.issues.push(`Generator can produce only ${p.unique}/3333 unique combinations with current traits/rules.`);a.pass=a.issues.length===0;state.plan=p;return a}
$("runAudit").onclick=()=>{const a=fullAudit();$("auditReport").textContent=a.pass?`PROJECT PASS\nGenesis locked and valid\nApproved traits: ${approvedTraits().length}\nConflicts valid\n3,333 unique combinations verified\n64×64 → 4096 exact ×64 path ready`:`PROJECT NOT READY\n`+a.issues.join("\n");for(const id of ["exportAssetZip","exportMetadataZip","renderBatch"])$(id).disabled=!a.pass;setAppStatus(a.pass?"PROJECT PASS":"AUDIT FAIL")};
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
const u16=n=>[n&255,n>>>8&255],u32=n=>[n&255,n>>>8&255,n>>>16&255,n>>>24&255],sb=s=>enc.encode(s);
function zip(entries){let chunks=[],central=[],off=0;for(const e of entries){const name=sb(e.name),data=e.data instanceof Uint8Array?e.data:new Uint8Array(e.data),crc=crc32(data),local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...name]);chunks.push(local,data);central.push(new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(off),...name]));off+=local.length+data.length}const co=off,cs=central.reduce((s,c)=>s+c.length,0);chunks.push(...central,new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(entries.length),...u16(entries.length),...u32(cs),...u32(co),...u16(0)]));return new Blob(chunks,{type:"application/zip"})}
async function pngBytes(p,size=64){const c=document.createElement("canvas");c.width=c.height=size;const x=c.getContext("2d");x.imageSmoothingEnabled=false;x.drawImage(canvas64FromPixelsImpl(p),0,0,size,size);const b=await new Promise(r=>c.toBlob(r,"image/png"));return new Uint8Array(await b.arrayBuffer())}
$("exportAssetZip").onclick=async()=>{const a=fullAudit();if(!a.pass)return;const e=[{name:"Body/Brown.png",data:await pngBytes(state.genesis,64)}];for(const t of approvedTraits()){e.push({name:`${t.category}/${safe(t.name)}.png`,data:await pngBytes(t.pixels,64)});if(t.mask.some(v=>v)){const mp=C.makePixels();for(let c=0;c<CELLS;c++)if(t.mask[c]){let i=c*4;mp[i]=mp[i+1]=mp[i+2]=255;mp[i+3]=255}e.push({name:`Masks/${t.category}/${safe(t.name)}_mask.png`,data:await pngBytes(mp,64)})}}e.push({name:"project_manifest.json",data:sb(JSON.stringify(C.serializeProject(projectForCore()),null,2))});download(zip(e),"APE16_ASSET_LIBRARY.zip")};
$("exportMetadataZip").onclick=()=>{const a=fullAudit();if(!a.pass)return;const e=[],manifest=[];state.plan.items.forEach((item,i)=>{const token=i+1,meta=C.metadataFor(token,item,state.settings);e.push({name:`metadata/${token}.json`,data:sb(JSON.stringify(meta,null,2))});manifest.push({token,traits:item.map(t=>({category:t.category,name:t.name}))})});e.push({name:"combination_plan.json",data:sb(JSON.stringify(manifest,null,2))});e.push({name:"collection.json",data:sb(JSON.stringify(state.settings,null,2))});download(zip(e),"APE16_3333_METADATA_PLAN.zip")};
$("renderBatch").onclick=async()=>{const a=fullAudit();if(!a.pass)return;let start=Number($("batchStart").value),end=Number($("batchEnd").value),size=Number($("renderSize").value);if(start<1||end>3333||end<start)return alert("Invalid token range.");const count=end-start+1,limit=size===4096?25:size===1024?250:1000;if(count>limit)return alert(`For iPad safety, ${size}×${size} batches are limited to ${limit} images.`);$("batchStatus").textContent=`Rendering ${count} images...`;const e=[];for(let token=start;token<=end;token++){const item=state.plan.items[token-1],p=C.compose(state.genesis,productionTraitsFromPlanItem(item));e.push({name:`images/${token}.png`,data:await pngBytes(p,size)});$("batchStatus").textContent=`Rendered ${token-start+1}/${count}`;await new Promise(r=>setTimeout(r,0))}download(zip(e),`APE16_IMAGES_${start}-${end}_${size}.zip`);$("batchStatus").textContent=`Batch ${start}-${end} complete.`};
function selfTest(){
 const r={};function t(n,v){r[n]=!!v}
 let p=C.makePixels();C.setRGBA(p,1,1,[1,2,3,255]);t("atomic cell",C.rgbaAt(p,1,1)[0]===1);let q=C.clonePixels(p);C.floodFill(q,0,0,[9,9,9,255]);t("fill",C.rgbaAt(q,0,0)[0]===9&&C.rgbaAt(q,1,1)[0]===1);t("line",C.lineCells(0,0,5,5).length===6);t("rect",C.rectCells(0,0,2,2,false).length===8);let m=C.makeMask();C.applyMaskBrush(m,2,2,1);t("mask",m[C.idx(2,2)]===1);let comp=C.compose(p,[{category:"Headwear",pixels:q,mask:m,none:false}]);t("compose",comp.length===16384);t("alpha validation",C.validatePixels(p).pass);let bad=C.clonePixels(p);bad[3]=127;t("partial alpha reject",!C.validatePixels(bad).pass);t("scale",4096/64===64);let rr=C.rng("x"),a=rr(),rr2=C.rng("x");t("deterministic RNG",a===rr2());const pass=Object.values(r).every(Boolean);$("selfTest").textContent=`SELFTEST ${pass?"PASS":"FAIL"} · ${Object.keys(r).length} checks`;return {pass,r}
}
loadGenesis();renderLibrary();selfTest();
})();