(()=>{"use strict";const $=id=>document.getElementById(id);const state={n:64,zoom:8,cells:[],undo:[],redo:[],tool:"pencil",drawing:false,reference:null};const idx=(x,y)=>y*state.n+x;const empty=n=>Array.from({length:n*n},()=>null);const rgba=h=>{h=h.replace("#","");return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),255]};const css=v=>`rgba(${v[0]},${v[1]},${v[2]},${v[3]/255})`;
function resize(){const c=$("canvas");c.width=state.n*state.zoom;c.height=state.n*state.zoom;$("zoomLabel").textContent=`${state.zoom}× display zoom`}
function draw(){const c=$("canvas"),x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);if(state.reference&&$("showReference").checked){let op=+$("refOpacity").value/100,sc=+$("refScale").value/100,ox=+$("refX").value/100,oy=+$("refY").value/100,w=state.reference.width,h=state.reference.height,fit=Math.min(state.n/w,state.n/h)*sc,dw=w*fit*state.zoom,dh=h*fit*state.zoom,px=(c.width-dw)/2+ox*c.width,py=(c.height-dh)/2+oy*c.height;x.save();x.globalAlpha=op;x.imageSmoothingEnabled=false;x.drawImage(state.reference,px,py,dw,dh);x.restore()}for(let y=0;y<state.n;y++)for(let z=0;z<state.n;z++){const v=state.cells[idx(z,y)];if(v){x.fillStyle=css(v);x.fillRect(z*state.zoom,y*state.zoom,state.zoom,state.zoom)}}if($("showGrid").checked&&state.zoom>=5){x.strokeStyle="rgba(120,120,120,.28)";x.lineWidth=1;x.beginPath();for(let i=0;i<=state.n;i++){let p=i*state.zoom+.5;x.moveTo(p,0);x.lineTo(p,c.height);x.moveTo(0,p);x.lineTo(c.width,p)}x.stroke()}}
function reset(n){state.n=n;state.cells=empty(n);state.undo=[];state.redo=[];resize();draw()}
function saveUndo(){state.undo.push(state.cells.slice());if(state.undo.length>100)state.undo.shift();state.redo=[]}
function setc(x,y,v,mir=true){if(x<0||y<0||x>=state.n||y>=state.n)return;state.cells[idx(x,y)]=v?v.slice():null;if(mir&&$("mirrorX").checked){let mx=state.n-1-x;if(mx!==x)state.cells[idx(mx,y)]=v?v.slice():null}}
function same(a,b){if(a===null&&b===null)return true;if(!a||!b)return false;return a.every((v,i)=>v===b[i])}
function fill(sx,sy,v){let start=state.cells[idx(sx,sy)];if(same(start,v))return;let q=[[sx,sy]],seen=new Set;while(q.length){let[x,y]=q.pop(),k=x+","+y;if(seen.has(k)||x<0||y<0||x>=state.n||y>=state.n)continue;seen.add(k);if(!same(state.cells[idx(x,y)],start))continue;setc(x,y,v,false);q.push([x+1,y],[x-1,y],[x,y+1],[x,y-1])}}
function cell(e){let r=$("canvas").getBoundingClientRect();return{x:Math.floor((e.clientX-r.left)/(r.width/state.n)),y:Math.floor((e.clientY-r.top)/(r.height/state.n))}}
function apply(x,y,first=false){if(x<0||y<0||x>=state.n||y>=state.n)return;if(first)saveUndo();if(state.tool==="pencil")setc(x,y,rgba($("color").value));else if(state.tool==="eraser")setc(x,y,null);else if(state.tool==="fill")fill(x,y,rgba($("color").value));else if(state.tool==="picker"){let v=state.cells[idx(x,y)];if(v)$("color").value="#"+v.slice(0,3).map(n=>n.toString(16).padStart(2,"0")).join("")}draw()}
$("canvas").onpointerdown=e=>{e.preventDefault();let p=cell(e);state.drawing=true;$("canvas").setPointerCapture(e.pointerId);apply(p.x,p.y,true)};$("canvas").onpointermove=e=>{let p=cell(e);$("coord").textContent=`x: ${p.x} y: ${p.y}`;if(state.drawing&&(state.tool==="pencil"||state.tool==="eraser"))apply(p.x,p.y)};$("canvas").onpointerup=()=>state.drawing=false;$("canvas").onpointercancel=()=>state.drawing=false;
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;document.querySelectorAll("[data-tool]").forEach(q=>q.classList.toggle("active",q===b))});
$("undoBtn").onclick=()=>{if(!state.undo.length)return;state.redo.push(state.cells.slice());state.cells=state.undo.pop();draw()};$("redoBtn").onclick=()=>{if(!state.redo.length)return;state.undo.push(state.cells.slice());state.cells=state.redo.pop();draw()};$("clearBtn").onclick=()=>{if(confirm("Clear current layer?")){saveUndo();state.cells=empty(state.n);draw()}};
$("resolution").onchange=e=>{let n=+e.target.value;if(state.cells.some(Boolean)&&!confirm("Changing resolution clears the layer. Continue?")){e.target.value=state.n;return}reset(n)};$("zoom").oninput=e=>{state.zoom=+e.target.value;resize();draw()};["showGrid","showReference","refOpacity","refScale","refX","refY"].forEach(id=>$(id).oninput=draw);
$("referenceFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let im=new Image;im.onload=()=>{state.reference=im;draw();URL.revokeObjectURL(im.src)};im.src=URL.createObjectURL(f)};
const colors=["#000000","#1a1a1a","#4b230d","#74360f","#9b4a16","#c66a2d","#f0a15f","#ffc184","#ffffff"];colors.forEach(h=>{let b=document.createElement("button");b.className="swatch";b.style.background=h;b.onclick=()=>{$("color").value=h};$("palette").appendChild(b)});
function logical(){let c=document.createElement("canvas");c.width=state.n;c.height=state.n;let x=c.getContext("2d");for(let y=0;y<state.n;y++)for(let z=0;z<state.n;z++){let v=state.cells[idx(z,y)];if(v){x.fillStyle=css(v);x.fillRect(z,y,1,1)}}return c}
function download(c,name){c.toBlob(blob=>{let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1200)},"image/png")}
$("exportMasterBtn").onclick=()=>download(logical(),`APE16_${state.n}x${state.n}.png`);$("export1024Btn").onclick=()=>{let s=logical(),o=document.createElement("canvas");o.width=o.height=1024;let x=o.getContext("2d");x.imageSmoothingEnabled=false;x.drawImage(s,0,0,1024,1024);download(o,"APE16_1024_preview.png")};
$("importLayerBtn").onclick=()=>$("importLayerFile").click();$("importLayerFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let im=new Image;im.onload=()=>{if(im.width!==state.n||im.height!==state.n){alert(`PNG must be exactly ${state.n}×${state.n}`);return}let c=document.createElement("canvas");c.width=c.height=state.n;let x=c.getContext("2d");x.drawImage(im,0,0);let d=x.getImageData(0,0,state.n,state.n).data;saveUndo();for(let i=0;i<state.n*state.n;i++)state.cells[i]=d[i*4+3]===0?null:[d[i*4],d[i*4+1],d[i*4+2],d[i*4+3]];draw()};im.src=URL.createObjectURL(f)};
reset(64);})();